services:
  - type: web
    name: stock-prediction-api
    runtime: docker
    rootDir: backend-drf
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"